spring:
  boot:
    admin:
      client:
        url: http://localhost:8099
        username: tf-admin-user
        password: password123
        instance:
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}