eureka:
  client:
    registerWithEureka: ${APP_DISCOVERY_REGISTER_WITH_EUREKA:false}
    fetchRegistry:  ${APP_DISCOVERY_FETCH_REGISTRY:false}
    service-url:
      defaultZone: http://tf-discovery-user:password123@localhost:8761/eureka
