server:
  port: ${APP_ADMIN_SERVER_PORT:8099}
spring:
  profiles:
    include:
      - admin-client
  threads:
    virtual:
      enabled: ${APP_ADMIN_ENABLE_VIRTUAL_THREAD:true}
  security:
    user:
      name: tf-admin-user
      password: password123
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ${logging.file.name}
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: logs/admin-service.log
