server:
  port: ${APP_CONFIG_SERVER_PORT:8090}
spring:
  profiles:
    include:
      - admin-client
      - config-client
  cloud:
    config:
      server:
        git:
          uri: ${APP_GIT_URL}
          username: ${APP_GIT_USERNAME}
          password: ${APP_GIT_PASSWORD}
          clone-on-start: true
          default-label: ${APP_GIT_BRANCH:main} # for git branches
  threads:
    virtual:
      enabled: ${APP_CONFIG_ENABLE_VIRTUAL_THREAD:true}
  security:
    user:
      name: tf-config-user
      password: password123
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ${logging.file.name}
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: logs/config-service.log
